name: Format, lint, test, build, and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  format_lint_test:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.16
      uses: actions/setup-node@v4
      with:
        node-version: 20.16
        cache: 'npm'
    - name: Install dev dependencies
      run: npm ci

    - name: Check formatting with Prettier
      run: npm run prettier:check
    
    - name: Lint with eslint
      run: npm run lint

    - name: Test with Vitest
      run: npm run test

    - name: Build
      run: npm run build

    - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOERACITY_ALPHA_1 }}
          channelId: live
          projectId: voeracity-alpha-1